title: linjan2 takes notes
author: Linda Jansson
email: null
description: 
source_repo: https://github.com/linjan2/linjan2.github.io
baseurl: ''
url: linjan2.github.io
github_username: linjan2

theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: '' # all
    values:
      author: Linda Jansson
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      permalink: /:categories/:title/
  - scope:
      path: pages
    values:
      layout: page
